# Generated by Django 5.0.2 on 2024-03-01 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название команды')),
            ],
        ),
        migrations.CreateModel(
            name='HockeyPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя игрока')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия игрока')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='команда', to='whatsapp.team')),
            ],
        ),
    ]
