# Generated by Django 5.0.2 on 2024-03-01 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hockeyplayer',
            name='team',
        ),
        migrations.AddField(
            model_name='hockeyplayer',
            name='team',
            field=models.ManyToManyField(to='whatsapp.team'),
        ),
    ]
