# Generated by Django 5.0.2 on 2024-03-12 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0007_contact_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Representative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=10, verbose_name='Статус представителя команды')),
                ('first_name', models.CharField(max_length=20, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=20, null=True, verbose_name='Фамилия')),
                ('surname', models.CharField(max_length=20, null=True, verbose_name='Отчество')),
                ('phone', models.IntegerField(verbose_name='Телефон')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(blank=True, choices=[('Нет', 'Нет'), ('Думают', 'Думают'), ('Будут', 'Будут'), ('Жду', 'Жду'), ('Гарантия', 'Гарантия')], max_length=8, null=True, verbose_name='Решение команды')),
                ('comment', models.CharField(max_length=255, null=True, verbose_name='Комментарий')),
                ('last_message', models.DateTimeField(verbose_name='Дата последнего сообщения')),
            ],
        ),
        migrations.RemoveField(
            model_name='team',
            name='rodkom',
        ),
        migrations.RemoveField(
            model_name='team',
            name='trener',
        ),
        migrations.RemoveField(
            model_name='team',
            name='an',
        ),
        migrations.RemoveField(
            model_name='team',
            name='team',
        ),
        migrations.RemoveField(
            model_name='team',
            name='uroven',
        ),
        migrations.AddField(
            model_name='team',
            name='distance_to',
            field=models.CharField(max_length=50, null=True, verbose_name='до Апрелевки'),
        ),
        migrations.AddField(
            model_name='team',
            name='level',
            field=models.CharField(max_length=10, null=True, verbose_name='Уровень'),
        ),
        migrations.AddField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='team',
            name='town',
            field=models.CharField(max_length=50, null=True, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='team',
            name='represent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='representative', to='whatsapp.representative'),
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('town', models.CharField(max_length=50, verbose_name='Город')),
                ('ice_rink', models.CharField(max_length=50, verbose_name='Название катка')),
                ('data', models.DateTimeField(verbose_name='Даты проведения')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status', to='whatsapp.status')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team', to='whatsapp.team')),
            ],
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Rodkom',
        ),
        migrations.DeleteModel(
            name='Trener',
        ),
    ]
