# Generated by Django 5.0.2 on 2024-03-12 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0008_representative_status_remove_team_rodkom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='representative',
            name='status',
            field=models.CharField(choices=[('Родком', 'Родком'), ('Тренер', 'Тренер')], max_length=6, verbose_name='Статус представителя команды'),
        ),
        migrations.AlterField(
            model_name='status',
            name='comment',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='ice_rink',
            field=models.CharField(default='April_ice', max_length=50, verbose_name='Название катка'),
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='team',
        ),
        migrations.AlterField(
            model_name='tournament',
            name='town',
            field=models.CharField(default='Апрелевка', max_length=50, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='team',
            field=models.ManyToManyField(to='whatsapp.team'),
        ),
    ]
