# Generated by Django 5.0.2 on 2024-03-12 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0009_alter_representative_status_alter_status_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='representative',
            name='last_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='representative',
            name='surname',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='team',
            name='distance_to',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='до Апрелевки'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='data',
            field=models.DateField(verbose_name='Даты проведения'),
        ),
    ]
